services:
  #person-postgres
  person-postgres:
    image: postgres:17
    container_name: person-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: person
    volumes:
      - ./infrastructure/databases/person:docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 20

  #person-postgres
  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 20

  #person-postgres-exporter
  person-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: person-postgres-exporter
    depends_on:
      person-postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgres://postgres:postgres@person-postgres:5432/postgres?sslmode=disable
    ports:
      - "9188:9187"

  keycloak-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: keycloak-postgres-exporter
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: postgres://keycloak:keycloak@keycloak-postgres:5432/keycloak?sslmode=disable
    ports:
      - "9189:9187"